
/* 
   TASK 1 : BASELINE PERFORMANCE (NO INDEXES)
*/

/* 48. EXPLAIN Query */

EXPLAIN
SELECT
    s.first_name,
    s.last_name,
    c.course_name
FROM enrollments e
JOIN students s
ON s.student_id = e.student_id
JOIN courses c
ON c.course_id = e.course_id
WHERE s.enrollment_year = 2022;


/*
49. Query Plan Analysis

Before creating indexes, MySQL/PostgreSQL may perform
a Full Table Scan (MySQL) or Sequential Scan (PostgreSQL)
on students, enrollments, and courses.

This is acceptable for small tables but becomes slow
for large datasets.
*/


/*
50. Estimated Cost / Rows Examined

Record the EXPLAIN output generated by your database
and paste it here as comments.

Example:

id | select_type | table | type | possible_keys | rows
------------------------------------------------------
1  | SIMPLE      | s     | ALL  | NULL          | 8
1  | SIMPLE      | e     | ALL  | NULL          | 12
1  | SIMPLE      | c     | ALL  | NULL          | 5

Observation:
Full table scans are occurring.
*/



/* 
   TASK 2 : ADD INDEXES
*/


/* 51. Index on enrollment_year */

CREATE INDEX idx_students_enrollment_year
ON students(enrollment_year);


/* 52. Composite UNIQUE Index */

CREATE UNIQUE INDEX idx_enrollment_student_course
ON enrollments(student_id, course_id);


/* 53. Index on course_code */

CREATE INDEX idx_course_code
ON courses(course_code);


/* 54. Re-run EXPLAIN */

EXPLAIN
SELECT
    s.first_name,
    s.last_name,
    c.course_name
FROM enrollments e
JOIN students s
ON s.student_id = e.student_id
JOIN courses c
ON c.course_id = e.course_id
WHERE s.enrollment_year = 2022;


/*
Comparison Notes

Before Index:

Full Table Scan / Seq Scan

After Index:

Index Scan on students.enrollment_year

Performance improves because the database
can directly locate matching rows instead of
scanning the entire table.
*/


/* 55. Partial Index (PostgreSQL Only) */

CREATE INDEX idx_null_grade_students
ON enrollments(student_id)
WHERE grade IS NULL;


/*
For MySQL users:

MySQL does not support partial indexes.

You may write:

-- PostgreSQL only
CREATE INDEX idx_null_grade_students
ON enrollments(student_id)
WHERE grade IS NULL;
*/



/* 
   TASK 3 : N+1 PROBLEM DOCUMENTATION
*/


/*
56. N+1 Problem Example

Python Logic:

SELECT * FROM enrollments;

FOR EACH enrollment:
    SELECT first_name,last_name
    FROM students
    WHERE student_id = ?


If there are 12 enrollments:

1 query to fetch enrollments
+
12 queries to fetch students

Total = 13 queries

This is called N+1 Query Problem.
*/


/*
57. Optimized Solution

Use a single JOIN query instead.
*/

SELECT
    e.enrollment_id,
    CONCAT(s.first_name,' ',s.last_name) AS student_name,
    c.course_name,
    e.grade
FROM enrollments e
JOIN students s
ON e.student_id = s.student_id
JOIN courses c
ON e.course_id = c.course_id;


/*
58. Comparison

N+1 Version:
------------
13 database round trips

JOIN Version:
-------------
1 database round trip

Both produce identical results.

JOIN version is significantly faster.
*/


/*
59. Real World Scenario

If there are 10,000 enrollments:

N+1 Version:
------------
1 + 10,000
=
10,001 Queries

JOIN Version:
-------------
1 Query

Extra Queries Issued:
---------------------
10,000 additional queries

Hence JOIN / eager loading should always
be preferred in large applications.
*/

